### ISSUE TITLE
Previews get cropped

### ISSUE THREAD

**Issue by UnaiM** [blepping/ComfyUI-bleh#9]
I haven’t used ComfyUI in a while, but since I’ve updated Bleh (and ComfyUI), I’m getting square previews filled up with black to compensate the aspect ratio mismatch with what would have been a normal (Blegh-less) preview:

![image](https://github.com/user-attachments/assets/e1fd403a-1eb0-4f4e-8084-b4317db2e9d4)

In this example, I’m keen on seeing if there are any tiny people moving at the bottom of the image, but it gets cropped. A few months ago, I used to get uncropped previews without black padding; the node would be super tall as a result, but that was okay. Is there anything in the settings I can add/change to recover this behaviour? Here are the contents of my `blehconfig.yaml`:

```yaml
betterTaesdPreviews:
    enabled: true
    max_size: 768
    max_batch: 2
    max_batch_cols: 2
    throttle_secs: 1
    maxed_batch_step_mode: true
    skip_upscale_layers: -2
```
